---
x-general: &general
  #init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

x-media: &media-grp
  PUID: 1002
  PGID: 1002

x-plexdependant: &plexdependant
  init: true
  depends_on:
    - plex

name: plex

services:
  plex:
    <<: [*general]
    container_name: plex
    network_mode: host
    environment:
      <<: *media-grp
      VERSION: docker
    #ports:
    #  - "32400:32400" # access to the Plex Media Server
    #  - "1900:1900/udp" # access to the Plex DLNA Server
    #  - "5353:5353/udp" # older Bonjour/Avahi network discovery
    #  - "8324:8324/tcp" # controlling Plex for Roku via Plex Companion
    #  - "32410:32410/udp" # current GDM network discovery
    #  - "32412:32412/udp" # current GDM network discovery
    #  - "32413:32413/udp" # current GDM network discovery
    #  - "32414:32414/udp" # current GDM network discovery
    #  - "32469:32469/tcp" # access to the Plex DLNA Server
    #devices:
    #  - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker-data/plex:/config
      #- /mnt/docker-data/plex:/config
      - /mnt/MediaLibrary1:/library1:ro
      - /mnt/MediaLibrary2:/library2:ro
    image: lscr.io/linuxserver/plex:latest
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s

  tautulli:
    <<: [*general, *healthcheck, *plexdependant]
    image: tautulli/tautulli
    container_name: tautulli
    volumes:
      - ~/docker-data/tautulli:/config
    environment:
      <<: *media-grp
    ports:
      - 8181:8181

  kometa:
    <<: [*general, *plexdependant]
    container_name: kometa
    environment:
      <<: *media-grp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker-data/kometa:/config:rw
    image: kometateam/kometa
    env_file:
      - path: default.env
        required: true
      - path: kometa.env
        required: true

  imagemaid:
    <<: [*general, *healthcheck, *plexdependant]
    image: kometateam/imagemaid
    container_name: imagemaid
    environment:
      <<: *media-grp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker-data/imagemaid/config:/config:rw
      - "~/docker-data/plex/Library/Application Support/Plex Media Server:/plex:rw"

  letterboxd-plex-sync:
    <<: [*general, *plexdependant]
    container_name: letterboxd-plex-sync
    image: treysu/letterboxd-plex-sync:latest
    environment:
      <<: *media-grp
    env_file:
      - path: letterboxd.env
        required: true
      - path: default.env
        required: true

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-data/letterboxd-plex-sync/data:/app/data:rw # add in a data folder to store your lb to tmdb mapping CSV file.
